name: CI/CD

on:
    pull_request: 
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with: 
                fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Install Yarn
              run: npm install -g yarn

            - name: Install dependencies
              run: yarn install

            - name: Test
              run: yarn test:cov

            - name: Build
              run: yarn build

            - name: Render Deployment
              uses: sws2apps/render-deployment@v1.6.0
              with:
                serviceId: ${{ secrets.RENDER_SERVICE_ID }}
                apiKey: ${{ secrets.RENDER_API_KEY }}

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@v2.2.0
              with:
                projectBaseDir: src
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}